services:
  
  userdb:
    image: postgres:14
    container_name: qc_tool_userdb
    restart: always
    environment:
      POSTGRES_DB: qc_tool
      POSTGRES_USER: qc_user
      POSTGRES_PASSWORD: qc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qc_tool_network
    ports:
      - "5432:5432"   # optional: only needed if you want access from host
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VERSION

    image: eeacms/copernicus-qctool-frontend:latest
    ports:
      - 8000:8000
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - WORK_DIR=/mnt/qc_tool_work
      - SUBMISSION_DIR=/mnt/qc_tool_submission/submission
      - DB_ENGINE=postgres
      - POSTGRES_HOST=qc_tool_userdb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=qc_tool
      - POSTGRES_USER=qc_user
      - POSTGRES_PASSWORD=qc_password
      - FRONTEND_DB_PATH=/mnt/qc_tool_work/frontend.sqlite3
    networks:
      - qc_tool_network
    volumes:
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_uploads/uploads:/mnt/qc_tool_uploads/uploads
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_incoming/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_submission:/mnt/qc_tool_submission
      - /mnt/c/Users/jkadlec/gisat/src3/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - VERSION

    image: eeacms/copernicus-qctool-worker:latest
    shm_size: 1gb
    environment:
      - PRODUCT_DIRS
      - BOUNDARY_DIR=/mnt/qc_tool_boundary/boundaries
      - INCOMING_DIR=/mnt/qc_tool_incoming/incoming
      - INSPIRE_SERVICE_URL=http://localhost:8080/validator/v2/
      - PULL_JOB_URL=http://frontend:8000/pull_job
      - WORK_DIR=/mnt/qc_tool_work
      - LEAVE_SCHEMA=yes
    networks:
      - qc_tool_network
    volumes:
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_boundary:/mnt/qc_tool_boundary
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_incoming/incoming:/mnt/qc_tool_incoming/incoming
      - /mnt/c/Users/jkadlec/qc_tool/qc_tool_work:/mnt/qc_tool_work
      - /mnt/c/Users/jkadlec/gisat/src3/copernicus_quality_tools:/usr/local/src/copernicus_quality_tools

networks:
  qc_tool_network:
    driver: bridge

volumes:
  postgres_data:
